### ISSUE TITLE
The source file syntax does not appear to be compatible python3

### ISSUE THREAD

**Issue by Carlzkh** [storborg/livetest#8]
![image](https://user-images.githubusercontent.com/50096899/57984564-962db280-7a8f-11e9-9bf4-bfcaf30f5c39.png)
There are other problems with modifying source files, such as the import package not existing
![image](https://user-images.githubusercontent.com/50096899/57984576-beb5ac80-7a8f-11e9-9b1c-53319408f557.png)

**Comment by ghost** [comment]
Me too:

[fm@meinherz ~]$ uname -a
Linux meinherz.zerbricht 5.6.13-100.fc30.i686 #1 SMP Fri May 15 00:02:53 UTC 2020 i686 i686 i386 GNU/Linux

[fm@meinherz ~]$ pip3 -V
pip 19.0.3 from /usr/lib/python3.7/site-packages/pip (python 3.7)

[fm@meinherz ~]$ python3 -V
Python 3.7.7

[fm@meinherz ~]$ sudo pip3 install --upgrade livetest
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting livetest
  Using cached https://files.pythonhosted.org/packages/de/77/7ab378ff9e62013f1756b64b1553e126ba7b3f3598bc9c5c8fc508c13d55/livetest-0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-b9d24dgf/livetest/setup.py", line 9, in <module>
        import livetest
      File "/tmp/pip-install-b9d24dgf/livetest/livetest/__init__.py", line 110
        except CookieError, e:
                          ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-b9d24dgf/livetest/

You know already what the issue is: Exception syntax, has changed "except CookieError as e".
